# Generated by Django 5.1.3 on 2025-02-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_date',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=8.978675645342312e-05),
            preserve_default=False,
        ),
    ]
