# Generated by Django 5.1.3 on 2025-01-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_cart'),
        ('shipping_cart', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
